# Generated by Django 3.1.1 on 2021-04-20 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Squadre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('livello', models.IntegerField(default=0)),
                ('nazione', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Squadra',
                'verbose_name_plural': 'Squadre',
            },
        ),
        migrations.CreateModel(
            name='Tornei',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('squadre', models.ManyToManyField(related_name='partecipanti', to='tournament.Squadre')),
            ],
            options={
                'verbose_name': 'Torneo',
                'verbose_name_plural': 'Tornei',
            },
        ),
    ]
